# REFACTORING Data

## MX Data with minimal

### Concat with Columns DF

* Experimental notebook to optimize the data we save
* Plan is that we save MX FDB Targets and its columns and we merge it with our input datasets (in contrast of loading that data in the MX process).

In [1]:

import jtc
from jgtpy import JGTCDSSvc as cds

In [2]:
i="NZD/CAD"
t="D1"
use_fresh=False

In [3]:
if use_fresh:
  df=cds.get(i,t,use_full=True,use_fresh=True)
else:
  df=cds.read(i,t,use_full=True)

In [4]:
df.tail(4)

,BidOpen,BidHigh,BidLow,BidClose,AskOpen,AskHigh,AskLow,AskClose,Volume,Open,...,price_peak_above,price_peak_bellow,ao_peak_above,ao_peak_bellow,mfi_sq,mfi_green,mfi_fade,mfi_fake,mfi_sig,mfi_str
Date,,,,,,,,,,,,,,,,,,,,,
2024-07-27 21:00:00,0.81425,0.81516,0.81391,0.81391,0.81522,0.81675,0.81522,0.81562,120,0.814735,...,0,0,0,0,0,0,0,1,2,-+
2024-07-28 21:00:00,0.81391,0.81537,0.81174,0.81377,0.81562,0.81657,0.81180,0.81402,93427,0.814765,...,0,0,0,0,1,0,0,0,1,+-
2024-07-29 21:00:00,0.81377,0.81766,0.81276,0.81741,0.81402,0.81783,0.81342,0.81768,100109,0.813895,...,0,0,0,0,0,1,0,0,4,++
2024-07-30 21:00:00,0.81741,0.81791,0.81609,0.81771,0.81768,0.81807,0.81693,0.81780,6666,0.817545,...,0,0,0,0,0,0,0,1,2,-+

In [5]:

#calculate_target_variable_min_max
target_colname = "fdb_target"
jtc.set_target_variable_name(target_colname)
df_with_fdb=jtc.calculate_target_variable_min_max(df,target_colname=target_colname)

In [6]:
df_with_fdb.columns

Index(['BidOpen', 'BidHigh', 'BidLow', 'BidClose', 'AskOpen', 'AskHigh',
       'AskLow', 'AskClose', 'Volume', 'Open', 'High', 'Low', 'Close',
       'Median', 'ao', 'ac', 'jaw', 'teeth', 'lips', 'bjaw', 'bteeth', 'blips',
       'tjaw', 'tteeth', 'tlips', 'fh', 'fl', 'fh3', 'fl3', 'fh5', 'fl5',
       'fh8', 'fl8', 'fh13', 'fl13', 'fh21', 'fl21', 'fh34', 'fl34', 'fh55',
       'fl55', 'fh89', 'fl89', 'mfi', 'fdbb', 'fdbs', 'fdb', 'aoaz', 'aobz',
       'zlc', 'zlcb', 'zlcs', 'zcol', 'zone_sig', 'sz', 'bz', 'acs', 'acb',
       'ss', 'sb', 'price_peak_above', 'price_peak_bellow', 'ao_peak_above',
       'ao_peak_bellow', 'mfi_sq', 'mfi_green', 'mfi_fade', 'mfi_fake',
       'mfi_sig', 'mfi_str', 'tmax', 'tmin', 'p', 'l', 'fdb_target'],
      dtype='object')

In [7]:
df_with_fdb.tail(3)

,BidOpen,BidHigh,BidLow,BidClose,AskOpen,AskHigh,AskLow,AskClose,Volume,Open,...,mfi_green,mfi_fade,mfi_fake,mfi_sig,mfi_str,tmax,tmin,p,l,fdb_target
Date,,,,,,,,,,,,,,,,,,,,,
2024-07-28 21:00:00,0.81391,0.81537,0.81174,0.81377,0.81562,0.81657,0.81180,0.81402,93427,0.814765,...,0,0,0,1,+-,0.0,0.0,0.0,0.0,0.0
2024-07-29 21:00:00,0.81377,0.81766,0.81276,0.81741,0.81402,0.81783,0.81342,0.81768,100109,0.813895,...,1,0,0,4,++,0.0,0.0,0.0,0.0,0.0
2024-07-30 21:00:00,0.81741,0.81791,0.81609,0.81771,0.81768,0.81807,0.81693,0.81780,6666,0.817545,...,0,0,1,2,-+,0.0,0.0,0.0,0.0,0.0

In [8]:
all_columns=['BidOpen', 'BidHigh', 'BidLow', 'BidClose', 'AskOpen', 'AskHigh',
       'AskLow', 'AskClose', 'Volume', 'Open', 'High', 'Low', 'Close',
       'Median', 'ao', 'ac', 'jaw', 'teeth', 'lips', 'bjaw', 'bteeth', 'blips',
       'tjaw', 'tteeth', 'tlips', 'fh', 'fl', 'fh3', 'fl3', 'fh5', 'fl5',
       'fh8', 'fl8', 'fh13', 'fl13', 'fh21', 'fl21', 'fh34', 'fl34', 'fh55',
       'fl55', 'fh89', 'fl89', 'mfi', 'fdbb', 'fdbs', 'fdb', 'aoaz', 'aobz',
       'zlc', 'zlcb', 'zlcs', 'zcol', 'zone_sig', 'sz', 'bz', 'acs', 'acb',
       'ss', 'sb', 'price_peak_above', 'price_peak_bellow', 'ao_peak_above',
       'ao_peak_bellow', 'mfi_sq', 'mfi_green', 'mfi_fade', 'mfi_fake',
       'mfi_sig', 'mfi_str', 'tmax', 'tmin', 'p', 'l', 'fdb_target']

In [9]:

columns_to_drop=['BidOpen', 'BidHigh', 'BidLow', 'BidClose', 'AskOpen', 'AskHigh',
       'AskLow', 'AskClose','Median', 'ao', 'ac', 'jaw', 'teeth', 'lips', 'bjaw', 'bteeth', 'blips',
       'tjaw', 'tteeth', 'tlips', 'fh', 'fl', 'fh3', 'fl3', 'fh5', 'fl5',
       'fh8', 'fl8', 'fh13', 'fl13', 'fh21', 'fl21', 'fh34', 'fl34', 'fh55',
       'fl55', 'fh89', 'fl89', 'mfi', 'fdbb', 'fdbs', 'fdb', 'aoaz', 'aobz',
       'zlc', 'zlcb', 'zlcs', 'zcol', 'zone_sig', 'sz', 'bz', 'acs', 'acb',
       'ss', 'sb', 'price_peak_above', 'price_peak_bellow', 'ao_peak_above',
       'ao_peak_bellow', 'mfi_str', 'tmax', 'tmin', 'p', 'l']

In [10]:

from jgtutils.jgtconstants import (AO,FDB,FDBS,FDBB,ZLCB,ZLCS)
#keep only target_colname
simple_df=df_with_fdb[[target_colname,AO,FDB,FDBS,FDBB,ZLCB,ZLCS]].copy()

In [11]:
simple_df.tail(5)

                     fdb_target        ao  fdb  fdbs  fdbb  zlcb  zlcs
Date
2024-07-25 21:00:00         0.0 -0.300528    1     0     1     0     0
2024-07-27 21:00:00         0.0 -0.322714    0     0     0     0     0
2024-07-28 21:00:00         0.0 -0.338004    1     0     1     0     0
2024-07-29 21:00:00         0.0 -0.335650    0     0     0     0     0
2024-07-30 21:00:00         0.0 -0.315984    0     0     0     0     0

In [12]:
simple_df_with_ao_vector=jtc.get_fdb_ao_vector_window(simple_df)

simple_df_with_ao_vector

,fdb_target,ao,fdb,fdbs,fdbb,zlcb,zlcs,vaosc,vaobc
Date,,,,,,,,,
2011-01-19 22:00:00,0.0000,0.108713,0,0,0,0,0,0,0
2011-01-20 22:00:00,-0.0055,0.077683,1,0,1,0,0,0,0
2011-01-23 22:00:00,0.0000,0.062823,0,0,0,0,0,0,0
2011-01-24 22:00:00,0.0000,0.059783,0,0,0,0,0,0,0
2011-01-25 22:00:00,0.0000,0.036671,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
2024-07-25 21:00:00,0.0000,-0.300528,1,0,1,0,0,0,28
2024-07-27 21:00:00,0.0000,-0.322714,0,0,0,0,0,0,0
2024-07-28 21:00:00,0.0000,-0.338004,1,0,1,0,0,0,30
2024-07-29 21:00:00,0.0000,-0.335650,0,0,0,0,0,0,0
2024-07-30 21:00:00,0.0000,-0.315984,0,0,0,0,0,0,0

In [13]:
import pandas as pd

# What Now ?

* We have our fdb_target and related columns
* Which of them are we interested to save ?
* --Or what is it that we would like to know if we load it?

In [14]:
from mlutils import get_basedir,get_outfile_fullpath

In [15]:

# Save it 
columns_to_drop=['fdbs','fdbb','zlcb','zlcs','ao']
mx_cleared_df=simple_df_with_ao_vector.drop(columns=columns_to_drop).copy()
pn_mx_fdb_target = "mx_fdb_target"#simple_mx_df_with_ao_vector
ns_dev = "dev"
simple_mx_outfile=get_outfile_fullpath(i,t,use_full=True,ns=ns_dev,pn=pn_mx_fdb_target)

mx_cleared_df.to_csv(simple_mx_outfile,index=True)
print(f"Saved {simple_mx_outfile}")

Saved /var/lib/jgt/full/data/dev/NZD-CAD_D1_mx_fdb_target.csv

## Practices

### Load MLF

#### Full MLF

In [16]:

import realityhelper
mlf_pn = "mfi"

In [17]:

mlfdf=realityhelper.generate_mlf_feature_pattern(i,t,use_full=True,pn=mlf_pn)

INFO::Columns List from Higher TF to prep laggings using MLF: ['mfi_sq', 'mfi_sq_M1', 'mfi_sq_W1', 'mfi_green', 'mfi_green_M1', 'mfi_green_W1', 'mfi_fade', 'mfi_fade_M1', 'mfi_fade_W1', 'mfi_fake', 'mfi_fake_M1', 'mfi_fake_W1']  for patternname: mfi  --- WE WILL Want to Create this pattern columns with a Global Pattern columns reading that would use the PN and the Timeframes.
   Read TTF:  /var/lib/jgt/full/data/ttf/NZD-CAD_D1_mfi.csv
    Pattern:mfi Output columns :'/var/lib/jgt/full/data/mlf/NZD-CAD_D1_mfi_columns.csv'
INFO::MLF Saved to :  /var/lib/jgt/full/data/mlf/NZD-CAD_D1_mfi.csv

#### Lagging only

In [18]:
just_keep_lagging_columns=True
mlfdf_just_lagging_fealtures=realityhelper.generate_mlf_feature_pattern(i,t,use_full=True,pn=mlf_pn,just_keep_lagging_columns=just_keep_lagging_columns,save_to_csv=False)

INFO::Columns List from Higher TF to prep laggings using MLF: ['mfi_sq', 'mfi_sq_M1', 'mfi_sq_W1', 'mfi_green', 'mfi_green_M1', 'mfi_green_W1', 'mfi_fade', 'mfi_fade_M1', 'mfi_fade_W1', 'mfi_fake', 'mfi_fake_M1', 'mfi_fake_W1']  for patternname: mfi  --- WE WILL Want to Create this pattern columns with a Global Pattern columns reading that would use the PN and the Timeframes.
   Read TTF:  /var/lib/jgt/full/data/ttf/NZD-CAD_D1_mfi.csv

In [19]:
mlfdf_just_lagging_fealtures.tail(1)

,mfi_sq_lag_1,mfi_sq_lag_2,mfi_sq_lag_3,mfi_sq_lag_4,mfi_sq_lag_5,mfi_sq_M1_lag_1,mfi_sq_M1_lag_2,mfi_sq_M1_lag_3,mfi_sq_M1_lag_4,mfi_sq_M1_lag_5,...,mfi_fake_M1_lag_1,mfi_fake_M1_lag_2,mfi_fake_M1_lag_3,mfi_fake_M1_lag_4,mfi_fake_M1_lag_5,mfi_fake_W1_lag_1,mfi_fake_W1_lag_2,mfi_fake_W1_lag_3,mfi_fake_W1_lag_4,mfi_fake_W1_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2024-07-30 21:00:00,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,1,1,0,0


### Merge with MLF

#### Simulating we have just lags

* We drop columns to simulate we would have just our lagging columns saved

In [20]:


columns_to_drop_for_simulating_we_just_have_lags=['BidOpen', 'BidHigh', 'BidLow', 'BidClose', 'AskOpen', 'AskHigh',
       'AskLow', 'AskClose', 'Volume', 'Open', 'High', 'Low', 'Close',
       'Median', 'ao', 'ac', 'jaw', 'teeth', 'lips', 'bjaw', 'bteeth', 'blips',
       'tjaw', 'tteeth', 'tlips', 'fh', 'fl', 'fh3', 'fl3', 'fh5', 'fl5',
       'fh8', 'fl8', 'fh13', 'fl13', 'fh21', 'fl21', 'fh34', 'fl34', 'fh55',
       'fl55', 'fh89', 'fl89', 'mfi', 'fdbb', 'fdbs', 'fdb', 'aoaz', 'aobz',
       'zlc', 'zlcb', 'zlcs', 'zcol', 'zone_sig', 'sz', 'bz', 'acs', 'acb',
       'ss', 'sb', 'price_peak_above', 'price_peak_bellow', 'ao_peak_above',
       'ao_peak_bellow', 'mfi_sq', 'mfi_green', 'mfi_fade', 'mfi_fake',
       'mfi_sig', 'mfi_str', 'tmax', 'tmin', 'p', 'l']

In [21]:
for col in columns_to_drop_for_simulating_we_just_have_lags:
  if col in mlfdf.columns:
    mlfdf.drop(columns=[col],inplace=True)

In [22]:
mlfdf.tail(3)

,mfi_sq_M1,mfi_sq_W1,mfi_green_M1,mfi_green_W1,mfi_fade_M1,mfi_fade_W1,mfi_fake_M1,mfi_fake_W1,mfi_sq_lag_1,mfi_sq_lag_2,...,mfi_fake_M1_lag_1,mfi_fake_M1_lag_2,mfi_fake_M1_lag_3,mfi_fake_M1_lag_4,mfi_fake_M1_lag_5,mfi_fake_W1_lag_1,mfi_fake_W1_lag_2,mfi_fake_W1_lag_3,mfi_fake_W1_lag_4,mfi_fake_W1_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2024-07-28 21:00:00,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
2024-07-29 21:00:00,0,0,1,0,0,0,0,1,1,0,...,0,0,0,0,0,1,1,0,0,0
2024-07-30 21:00:00,0,0,1,0,0,0,0,1,0,1,...,0,0,0,0,0,1,1,1,0,0

In [23]:

pn_dev_mlf_lags = "mlf_lags"#simple_mx_df_with_ao_vector
ns_dev = "dev"
mlf_with_lags_outfilepath=get_outfile_fullpath(i,t,use_full=True,ns=ns_dev,pn=pn_dev_mlf_lags)

mlfdf.to_csv(mlf_with_lags_outfilepath,index=True)
print("Saved:",mlf_with_lags_outfilepath)

Saved: /var/lib/jgt/full/data/dev/NZD-CAD_D1_mlf_lags.csv

In [24]:
mlfdf.tail(1)

,mfi_sq_M1,mfi_sq_W1,mfi_green_M1,mfi_green_W1,mfi_fade_M1,mfi_fade_W1,mfi_fake_M1,mfi_fake_W1,mfi_sq_lag_1,mfi_sq_lag_2,...,mfi_fake_M1_lag_1,mfi_fake_M1_lag_2,mfi_fake_M1_lag_3,mfi_fake_M1_lag_4,mfi_fake_M1_lag_5,mfi_fake_W1_lag_1,mfi_fake_W1_lag_2,mfi_fake_W1_lag_3,mfi_fake_W1_lag_4,mfi_fake_W1_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2024-07-30 21:00:00,0,0,1,0,0,0,0,1,0,1,...,0,0,0,0,0,1,1,1,0,0

In [25]:
mx_cleared_df.tail(1)

                     fdb_target  fdb  vaosc  vaobc
Date
2024-07-30 21:00:00         0.0    0      0      0

#### Concat the Two Datasets

#### Its: Merge !!

In [26]:

#concat mlfdf with simple_mx_df_with_ao_vector using Date index
#result_df=pd.concat([mx_cleared_df,mlfdf],axis=1)
df1=pd.read_csv(simple_mx_outfile,index_col='Date',parse_dates=True)
df2=pd.read_csv(mlf_with_lags_outfilepath,index_col='Date',parse_dates=True)

In [27]:

result_df=pd.merge(df1,df2,how='inner',on='Date')

In [28]:
result_df

,fdb_target,fdb,vaosc,vaobc,mfi_sq_M1,mfi_sq_W1,mfi_green_M1,mfi_green_W1,mfi_fade_M1,mfi_fade_W1,...,mfi_fake_M1_lag_1,mfi_fake_M1_lag_2,mfi_fake_M1_lag_3,mfi_fake_M1_lag_4,mfi_fake_M1_lag_5,mfi_fake_W1_lag_1,mfi_fake_W1_lag_2,mfi_fake_W1_lag_3,mfi_fake_W1_lag_4,mfi_fake_W1_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2020-10-06 21:00:00,0.0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,0,0
2020-10-07 21:00:00,0.0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
2020-10-08 21:00:00,0.0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
2020-10-10 21:00:00,0.0,0,0,0,0,1,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
2020-10-11 21:00:00,0.0,0,0,0,0,1,0,0,0,0,...,1,1,1,1,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-07-25 21:00:00,0.0,1,0,28,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2024-07-27 21:00:00,0.0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2024-07-28 21:00:00,0.0,1,0,30,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2024-07-29 21:00:00,0.0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
2024-07-30 21:00:00,0.0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,1,1,0,0